### ISSUE TITLE
Home page basic layout

### ISSUE THREAD

**Issue by saheelsapovadia** [clubgamma/spotify-web-clone#1]
The Home page will have two main sections as in the screenshot below

1. Left section with navigation item
2. Right section with top bar

The current state is not logged in. Check out other issues with the login functionalities as well.

Please follow the guidelines given in the [CONTRIBUTING.md](https://github.com/clubgamma/spotify-web-clone/blob/main/CONTRIBUTING.md) for styling and project structure needs to be maintained.

![image](https://user-images.githubusercontent.com/59962703/135207316-6da3a61e-ca36-4e9f-acb3-8f5d67e6a946.png)

Happy hacking 🤩!

**Comment by Deeprana12** [comment]
Hey!! @saheelsapovadia  You can assign the task under me!!

**Comment by Deeprana12** [comment]
Done!!! @saheelsapovadia
