### ISSUE TITLE
Important tests for diffrent component and features

### ISSUE THREAD

**Issue by sudeep162002** [clubgamma/spotify-web-clone#14]
We can include some pen testing files to this repo which will help developers and maintainer.

**Comment by sudeep162002** [comment]
I want to do this can you please assign it to me.

**Comment by sudeep162002** [comment]
I have done this type of files before.

**Comment by saheelsapovadia** [comment]
Would love your contribution!
I don't have much experience in this though, I would definitely like to learn from you 😄.

**Comment by sudeep162002** [comment]
Yeah sure😊
