### ISSUE TITLE
Signup page

### ISSUE THREAD

**Issue by saheelsapovadia** [clubgamma/spotify-web-clone#2]
The Signup page will have the form with proper validation for each field

Add proper state management to each field so that it can be attached to the Redux state. There is a separate issue for implementing Redux state management for login/signup

![image](https://user-images.githubusercontent.com/59962703/135282782-7dcfb9d6-7f2e-4359-b7b1-33f8619f4e91.png)

Happy hacking 🤩!

**Comment by lytk4dev** [comment]
assign to me, pls

**Comment by heerpatell** [comment]
Can you assign this to me?

**Comment by saheelsapovadia** [comment]
@heerpatell sure😃!

**Comment by KarishmaVanwari** [comment]
Is this issue still open?

**Comment by saheelsapovadia** [comment]
@KarishmaVanwari sorry, I forgot to close this one.
