### ISSUE TITLE
Login page

### ISSUE THREAD

**Issue by saheelsapovadia** [clubgamma/spotify-web-clone#3]
The Login page will have the form with proper validation for each field

Reuse the style for Signup and Login page.

Add proper state management to each field so that it can be attached to the Redux state. There is a separate issue for implementing Redux state management for login/signup

![image](https://user-images.githubusercontent.com/59962703/135283828-3c915408-4744-4ec7-b7e3-b4f77128ec72.png)

**Comment by NirajGohel** [comment]
I want to work on this. can you assign this to me?

**Comment by shruti2710** [comment]
I would like to work on this issue for hacktoberfest 2021, can you assign this to me? @saheelsapovadia

**Comment by saheelsapovadia** [comment]
@NirajGohel Please contribute in timely manner as others are also waiting in line 🤟. 
@shruti2710  You can look for improvements once PR is received.

**Comment by NirajGohel** [comment]
ok, and can I use bootstrap?

**Comment by saheelsapovadia** [comment]
> ok, and can I use bootstrap?

I would insist on plain CSS to reduce the barriers for everyone who wishes to contribute.

**Comment by NirajGohel** [comment]
ok no problem with that

**Comment by NirajGohel** [comment]
@saheelsapovadia `react-router-dom` is missing in the package.json and in App.js 
`import Layout from "./Containers/Layout/Layout";` should be there.

**Comment by saheelsapovadia** [comment]
> @saheelsapovadia `react-router-dom` is missing in the package.json and in App.js `import Layout from "./Containers/Layout/Layout";` should be there.

You can install `react-router-dom` 
You can import all necessary components.

**Comment by NirajGohel** [comment]
That issue is solved and now everything is working

**Comment by NirajGohel** [comment]
This much is done. Unfortunately, I won't be able to finish this tonight due to other work. I will complete the remaining things tomorrow.

![image](https://user-images.githubusercontent.com/42432442/135641758-37ae100f-af60-483d-b85f-8f6a29374e72.png)

**Comment by saheelsapovadia** [comment]
> This much is done. Unfortunately, I won't be able to finish this tonight due to other work. I will complete the remaining things tomorrow.
> 
> ![image](https://user-images.githubusercontent.com/42432442/135641758-37ae100f-af60-483d-b85f-8f6a29374e72.png)

Keep it up! there's a lot more in store. 🚀
