### ISSUE TITLE
Gradient Bottom Banner

### ISSUE THREAD

**Issue by saheelsapovadia** [clubgamma/spotify-web-clone#4]
Add the Gradient Bottom Banner as show below

For a better understanding of the scope of this task, check all other issues as well.

![image](https://user-images.githubusercontent.com/59962703/135302504-457fd057-2ba1-4a1b-8408-6ea4f2817f4a.png)

Happy hacking 🤩!

**Comment by jagnani73** [comment]
Hi @saheelsapovadia!
I would like to work on this issue for hacktoberfest 2021, if you could assign it to me!

**Comment by jagnani73** [comment]
@saheelsapovadia unassigning myself since my PRs are complete, if no one takes it up, I will (-:

**Comment by saheelsapovadia** [comment]
> @saheelsapovadia unassigning myself since my PRs are complete, if no one takes it up, I will (-:

No issues 👌
Do share your experience on social media and tag club_gamma, it means a lot to us 💪🚀

**Comment by shruti2710** [comment]
Hi, @saheelsapovadia Can you assign this task to me ?

**Comment by saheelsapovadia** [comment]
> Hi, @saheelsapovadia Can you assign this task to me ?
Enjoy 🎉!

**Comment by saheelsapovadia** [comment]
@shruti2710 any updates?

**Comment by shruti2710** [comment]
Yes, I'm working on it DW! Some issue occurs with my laptop so I'm unable to push it, But I'll do it as soon as possible!
