### ISSUE TITLE
Add routing via react-router

### ISSUE THREAD

**Issue by saheelsapovadia** [clubgamma/spotify-web-clone#5]
Add the Routing functionality with the following basic routes -

1. Home
2. Signup
3. Login
4. Playlist
5. Artist
You are most welcomed to dig deeper and add more routes from the [Spotify](https://open.spotify.com/ ) site.

For a better understanding of the scope of this task, check all other issues as well.

Happy hacking 🤩!

**Comment by ikabir21** [comment]
assign it to me

**Comment by lytk4dev** [comment]
assign to me, pls

**Comment by jagnani73** [comment]
Hey @saheelsapovadia !
I would love to work on this issue if you could assign it to me!
